### ISSUE TITLE
Extra films ne fonctionnent pas

### ISSUE THREAD

**Issue by elfassy** [anisite/plugin.infologique.tou.tv#1]
Les émissions de télé extra fonctionnent mais pas les film. Merci pour cette application

**Comment by anisite** [comment]
Oui, malheureusement la plupart des films ou séries hors Canada ont des DRM, autrefois l'application affichait un message pour annoncer le non support, mais il y avait quelques faux positifs. Puisque kodi est incapable de gérer les certificats DRM il n'est pas possible de lui faire décoder les flux chiffrés...

**Comment by anisite** [comment]
@elfassy bonjour, une nouvelle version ici [https://github.com/anisite/plugin.infologique.tou.tv/tree/DRM](https://github.com/anisite/plugin.infologique.tou.tv/tree/DRM) permet de supporter les DRM, si vous voulez tester avant la version finale!

**Comment by gabtremblay** [comment]
Simplement pour confirmer que sur Android (shield tv), avec kodi 18 alpha 2, et en forcant le type de stream a widevine dans la config, le tout fonctionne parfaitement avec le contenu Extra, ainsi que les streams normaux.

**Comment by esenterre** [comment]
@gabtremblay Je suis avec une Xiaomi MiBox. Mais ça ne devrait pas être tellement différent. Peux-tu me dire où tu vois le type de stream à widevine ? J'essaie présentement Kodi 18Alpha3 et le contenu "Extra" ne semble pas fonctionner.

**Comment by anisite** [comment]
Il semble que certaines box android n'ont pas les licences drm widevine L1 et ont seulement le L3 c'est peut-être l'explication. Sur mon Chromebook non plus ça ne fonctionne pas mais la il n'y a rien que je peux faire c'est kodi qui ne supporte pas le processeur...

**Comment by anisite** [comment]
@esenterre peux tu m'envoyer le log de kodi en debug des qu'il plante après tentative de lecture?

**Comment by esenterre** [comment]
@anisite Je vais regarder ça, probablement demain. Mais il ne "plante" pas.  Sois j'ai un écran noir, ou parfois c'est un écran "vert" avec des textures bizarres. Quand je regarde dans Kodi, je vois le temps avancer. Je peux même faire STOP. Et essayer autre chose...

**Comment by anisite** [comment]
Tu peux aller dans la paramètres de l'addon (bouton de droit sur une souris ou je ne sais pas sur quoi sur la télécommande mais dans le menu de gauche je pense qu'il y a un raccourci) et dans les paramètres de l'addon ya justement le type de flux tu peux toujours forcer widevine et voir...

**Comment by esenterre** [comment]
Voici mon log : https://pastebin.com/AZdzF6KQ 

Je vais aller voir dans les paramètres de l'addon.

**Comment by esenterre** [comment]
Dans type de flux j'ai seulement HLS et RTSP. 
Kodi 18 Alpha 2.
Version 3.0.0 Beta 2 du Addon.

**Comment by esenterre** [comment]
Ok je viens de télécharger la version que tu as linkée plus haut (DRM).
Je viens de l'essayer et après avoir reparti Kodi, ça fonctionne avec WideVine!
Merci!

**Comment by anisite** [comment]
La version finale 3.0.1 est sortie aujourd'hui, SVP ré-ouvrir un bug ou ré-ouvrir celui-ci si vous rencontrez des difficultés.
