### ISSUE TITLE
tou.tv 4.04 ne fonctionne pas sur ma plateforme

### ISSUE THREAD

**Issue by pisabell2** [anisite/plugin.infologique.tou.tv#10]
Bonjour,

J'ai installé tou.tv 4.04 sur ma plateforme Chromebox qui roule kodi 17.6 sous libreelec 8.2.5.

L'installation semble se dérouler correctement et l'app tou.tv démarre et accepte mon nom d'utilisateur et mot de passe sans problème.

Malheureusement, les vidéos refusent de démarrer. Lorsque je clique sur un vidéo, quelques secondes (6-7) se passent sans réaction apparente; puis le logo "démarrage" apparaît brièvement (1-2 secondes) et le chargement s'arrête: le contrôle est rendu à l'utilisateur.

J'ai téléchargé le log KODI d'une session minimale avec tentative de chargement d'un vidéo tou.txv à l'URL suivant:
http://paste.kodi.tv/ogopugedof

Plusieurs message d'erreur apparaissent dans ce log mais je ne comprends pas leur cause/signification. Pouvez-vous m'aider SVP?

Merci à l'avance,

  Pierre

**Comment by anisite** [comment]
Bonjour!

Pouvez-vous svp vérifier que le plugin inputstream.adaptive est bien installé et qu'il n'est pas désactivé de votre kodi SVP ?

Kodi 18 supporte plus de format de vidéo sur plusieurs plateforme, c'est peut-etre le cas de la chromebox... difficile de supporter la version 17 avec le HLS.

**Comment by pisabell2** [comment]
Bonjour,

Merci de votre réponse.

J'ai vérifié que le plugin inputsream.adaptive est installé et qu'il n'est
pas désactivé.

Je suppose donc qu'il faudrait que je passe à KODI 18? J'ai essayé dele
faire il y a quelque temps et j'ai rencontré un problème: apparemment la
partition système de mon disque était trop petite. Je vais essayer de
trouver un correctif.

Merci beaucoup,

  Pierre

**Comment by anisite** [comment]
@pisabell2 ce n'est pas garantie que cela corrige le problème, mais sinon c'est le DRM qui est installé sur l'OS qui n'est pas valide, probablement qu'à ce moment là il n'y a rien à faire...

**Comment by davidbellemare** [comment]
@pisabell2 @anisite pour votre info meme avec Kodi 18 (j utilises 18.3) presque toutes les series ne decolle pas (ex: unite 9, les freres scott, la petite vie, etc) seulement quelques unes fonctionnent (ex: demain des hommes). J ai fais un fix de mon cote et tout fonctionnent maintenant, je vais ouvrir un PR dans les prochains jours.

**Comment by anisite** [comment]
@r1v3n  super beau travail!

**Comment by davidbellemare** [comment]
@anisite #11 est maintenant ouvert 👍

**Comment by pisabell2** [comment]
Bonjour,

Je ne suis pas vraiment familier avec les processus de github. Est-ce que
votre message signifie qu'une nouvelle version de l'app tou.tv sera bientôt
disponible?

Merci,

  Pierre

**Comment by davidbellemare** [comment]
Oui, en fait @anisite va regarder les changements que j' ai apporte et si il est d accord, il va les integrer et sortir une nouvelle version de l addon avec ceux ci.

**Comment by pisabell2** [comment]
Compris, merci beaucoup!

  Pierre

**Comment by anisite** [comment]
Désolé avec les vacances, j'ai pas toujours mon ordi avec moi et il est parfois impossible de prendre le temps de l'ouvrir... bref on n'arrête jamais ! je fais ce merge ce soir et je pousse la version d'ici 20 minutes

**Comment by davidbellemare** [comment]
Ouais c'est ce que je pensais. Moi j'ai eu un peu de temps ici et la de nuit lol .... conge parental :)

**Comment by anisite** [comment]
@pisabell2 @r1v3n version 4.1.0 déployée, il y a toujours le caching de github qui peut demander jusqu'à 8 heures avant que la version s'update de votre bord. tenez-moi au courant!

**Comment by davidbellemare** [comment]
Ca fonctionne bien jai updater. PTI ca na rien a voir avec github mais la frequence a laquelle kodi fais son check d update de tes repos (je crois que c est jusqua 12h meme, mais p-e 8 aussi). Mais c est possible de forcer un check d updates (Check for updates dans le repo).

**Comment by anisite** [comment]
@r1v3n oui c'est jusqu'à 12 heures, mais ce n'est pas seulement la faute de kodi, github met dans l'entête http une expiration du fichier dans plusieurs heures pour soulager ses serveurs... puisque ce n'est pas fait pour distribuer du contenu, possible que kodi passe outre, mais ce n'est pas toujours le cas. tant mieux si ça marche!

**Comment by pisabell2** [comment]
Bonjour,

J'ai installé 4.1.0 sur mon kodi et malheureusement ça ne fonctionne
toujours pas pour moi. J'ai essayé toutes les combinaisons de flux
(widevine, rtsp, etc) et de DRM on/off et rien n'y fait.

Voici deux logs obtenus chacun avec une combinaison différente des valeurs
en question:

  http://paste.kodi.tv/sehabucexu

  http://paste.kodi.tv/avusikupet


Concernant la ligne suivante qui apparaît dans les deux fichiers (382 dans
un cas, 372 dans l'autre),

<code>

2019-07-31 12:35:47.883 T:140500104922880   ERROR: GetDirectory -
Error getting /usr/lib/kodi/addons/inputstream.adaptive/

</code>

 je remarque que le fichier  inputstream.adaptative se trouve plutôt à
l'emplacement suivant:

<code>
/storage/.kodi/addons/inputstream.adaptive
</code>

Je ne sais pas si c'est là le problème et si oui comment le corriger.

Merci à l'avance de vos suggestions.

  Pierre

p.s. l'input adaptatif est installé et actif. J'ai aussi mis à jour ma
config générale: c'est maintenant kodi 18

**Comment by davidbellemare** [comment]
Il ne trouve pas inputstream.adaptative et widevine, donc ca ne peut pas marcher sans ca. Tu pourrais toujours tester en deletant ta config complete de Kodi et repartir scratch et j imagine que ca fonctionnerais.

**Comment by pisabell2** [comment]
Merci de ce commentaire.

Toiutefois, avant d'essayer 4.1 je venais juste de réinstaller libreelec 9
avec kodi 18 from scratch et de faire un restore de la config précédente
que j'avais sauvegardée, pour ne pas être obligé de  réinstaller toutes mes
applications.

Est-ce que je devrais recommencer l'installation de libreelec from scratch
et essayer tou.tv 4.1 sans faire de restore de ma vieille config?

Merci,

  Pierre

**Comment by davidbellemare** [comment]
Je ne ferais pas de restore. Clean install de kodi plus l addon seulement, peut-etre quelque chose dans la config qui change des paths.

**Comment by pisabell2** [comment]
Ok, je vien d'essayer le clean install suivi immédiatement de l'intallation
de tou.tv 4.1 et ça fonctionne! Après, j.ai refait un restore. Ceci a remis
la vieille version de tou.tv. Après avoir réinstallé 4.1, comme je le
craignais, ça ne fonctionne plus.

Je pense que je suis quitte pour tout réinstaller en neuf! C'est un peu
barbant, surtout le backbone de télé tvheadend, mais bon...

Merci,

  Pierre

**Comment by davidbellemare** [comment]
Bonne nouvelle :)

**Comment by ko570a** [comment]
Je n'ai jamais réussi à faire fonctionner tou.tv sur android. Je l'ai installé, mais quand je clique sur une video, j'ai le son mais l'image est déformée, on ne distingue rien. J'ai input adaptive installé mais ça ne fonctionne toujours pas. Aussi sur dépot-québec, j'ai pris les autres additiels tels TV5 et Unis, mais ils ne fonctionnent pas. Le seul additiel qui fonctionne est TVA.
 J'aimerais bien savoir pourquoi ça ne fonctionne pas pour moi sur Android. J'ai Leia 18.2 et android 8.1 sur tablette Samsung tabA 10 po. Aussi, j'ai désinstallé kodi et réinstallé tout en neuf et ça ne fonctionne toujours pas.

**Comment by ko570a** [comment]
Je crois que j'ai trouvé pourquoi sur cette page: https://github.com/google/ExoPlayer/issues/3775
Ma tablette est une samsung t580 comme dans la page du lien et il y a un problème pour cette tablette avec widevine.
