### ISSUE TITLE
Impossible de lire un vidéo Tou.tv v4.1.0

### ISSUE THREAD

**Issue by franckgaga** [anisite/plugin.infologique.tou.tv#13]
Le plugin ne semble plus fonctionner (Librelec v9.1.002 sur RPi 3B+). Je peux naviguer dans les menus mais impossible de lire un vidéo. Mon plugin Netflix m'a récemment demander d'updater widevine en téléchargeant les fichiers de chromeos, c'est peut être relié ?

Merci!

**Comment by franckgaga** [comment]
Log file :
http://ix.io/1SSM

**Comment by anisite** [comment]
Est-ce le même problème que celui ci https://github.com/anisite/plugin.infologique.tou.tv/issues/12

**Comment by franckgaga** [comment]
Ça semble être la même chose mais il ne me propose pas de re-télécharger widevine. Je ne comprends pas trop comment l'installer manuellement...

**Comment by anisite** [comment]
le plugin netflix lui s'Est remis a marcher?

**Comment by franckgaga** [comment]
Oui, le plugin Netflix m'avait proposé de télécharger widevine il y a quelques jours, je lai fait, et netflix fonctionne bien depuis. Les deux plugins ne sont-ils pas supposé utiliser le même fichiers widevine d'ailleurs ? Si oui, tou.tv devrait fonctionner puisque netflix fonctionne... ??

**Comment by service-paradis** [comment]
J'ai eu le même problème. Widevine était déjà installé et Netflix fonctionnait correctement. Par contre, les vidéos sur tout.tv ne fonctionnait plus.

Une mise à jour manuelle de Widevine s'est imposé et tout fonctionne maintenant correctement (procédure assez technique malheureusement). Voici ce que j'ai fait (raspberry pi 2):

1. Connexion à OSMC en SSH
2. Exécution des commandes suivantes:
```
sudo su
mkdir /usr/lib/chromium-browser
cd /usr/lib/chromium-browser
wget http://blog.vpetkov.net/wp-content/uploads/2019/08/libwidevinecdm.so_.zip
 unzip libwidevinecdm.so_.zip && chmod 755 libwidevinecdm.so
cp -ar libwidevinecdm.so /home/osmc/.kodi/cdm/
```

**Comment by anisite** [comment]
oui. et je viens de regarder le code de netflx, c'est pareil, même version. mais il y a eu une update de script.module.inputstreamhelper peut-être que mon plugin ne l'a pas vu... sinon il est possible que le plugin met en cache l'info pour 7 jours et qu'il ne crois pas utile de revalider le libwidevine, tu peux p-e essayer de désinstaller toutv et le réinstaller, sinon je vais faire une mise a jour pour forcer la version 0.3.5 du script.module.inputstreamhelper

**Comment by franckgaga** [comment]
Finalement j'ai chercher l'emplacement de `libwidevinecdm.so`, qui se trouvait dans le répertoire `/storage/.kodi/cdm`. Le fichier n'était pas un vrai fichier mais un lien (brisé) qui pointait vers un fichier non existant (mais Netflix fonctionne pareil !?) : 

`storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm/libwidevinecdm.so`

J'ai donc seulement effacé le fichier lien `libwidevinecdm.so` et Tou.tv m'a proposé de télécharger widevine. Tou.tv et Netflix fonctionne maintenant.

Merci !
