### ISSUE TITLE
Comportement innatendu lors d'ajout d'un vidéo dans les favoris de Kodi

### ISSUE THREAD

**Issue by krazyking00** [anisite/plugin.infologique.tou.tv#16]
Bonjour,

Tout d'abord, félicitation pour cette extension géniale. C'est une de ceux que j'utilise le plus et elle est vraiment très bien fait. Je partage avec vous un problème lors d'ajout de vidéo en favoris. Voici les détails :

Si j'ajoute n'importe quel vidéo provenant de l'extension tou.tv dans les favoris de Kodi, j'ai de la difficulté à le faire jouer par la suite. Si je clique le lien créé dans les favoris, le vidéo démarre mais le chargement ne se termine pas correctement.

Étapes pour reproduire le problème
1. Dans un Kodi vierge, installer l'extension tou.tv et ses dépendances
2. Dans les configuration de l'extension, s'authentifier au compte EXTRA, ou non
3. Démarrer l'extension tou.tv et naviguer le contenu
4. Ajouter n'importe quel vidéo dans les favoris de Kodi (Add to favorites)
5. Retourner à l'accueil de Kodi
6. Aller dans les favoris de Kodi et démarrer un vidéo

Comportement observé:
- Le vidéo démarre mais l'animation de progression de téléchargement (rond bleu sous le skin Estuary) reste affiché pendant la durée complète du vidéo
- Dans le lecteur Kodi, les boutons de recule et avance ne sont pas disponible
- Si je clique le bouton de retour (back), un message d'erreur s'affiche et le vidéo s'arrête
- En contrepartie, si je démarre le même vidéo directement dans l'application tou.tv, ça fonctionne très bien

Comportement attendu:
- L'animation de progression de téléchargement (rond bleu sous le skin Estuary) devrait se cacher une fois que le vidéo est démarré
- Dans le lecteur Kodi, les fonctionnalités de recule et avance devrait être disponible

Informations supplémentaires
- Le problème observé est autant pour les vidéos gratuits que les vidéos EXTRA
- J'ai comparé les logs de Kodi lorsque le vidéo est démarré directement dans l'application et le résultat est identique
- J'ai le même comportement lorsque j'ajoute le vidéo dans SuperFavorites

Configurations
Extension tou.tv version 4.1.1
Kodi Leia version 18.4
Testé sous PC, Android box et Amazon Fire Stick

Merci pour votre temps, c'est très apprécié.
Je suis disponible pour aider et faire des tests.

**Comment by anisite** [comment]
Mon dieu quel détails! Désolé de ne pas avoir pu venir ici avant. Je peux jeter un œil la dessus, le plugin Netflix par exemple ne fait pas cela? C'est possiblement un bug avec toute la gestion des lus ou non lus, vous ne pouvez pas simplement utiliser les favoris de tou.tv directement? En gros je n'ai jamais vraiment supporté l'ajout aux favoris de Kodi, par paresse mais dès que j'ai 2 min je regarde d'où ça peut venir. Merci!

**Comment by krazyking00** [comment]
Salut, merci du retour. Malheureusement, je ne suis pas en mesure de vérifier pour Netflix car je n'ai pas de compte.

En fait, le problème se produit aussi avec les fichiers STRM, donc, à ma connaissance, il n'y a pas d'alternative pour arriver à mes fins.

J'ai fais quelques modifications dans le code et réglé le problème de mon côté. De mémoire, je crois avoir corriger le problème en ajoutant cette (deuxième) ligne dans le module TouTvPlayer :
player.play( url, listitem )
xbmcplugin.setResolvedUrl(__handle__, True, listitem) #Fix busy indicator not hiding when started from STRM or favorites

J'ai peu de connaissance dans le développement de plugin de Kodi. Je te laisse vérifier si ça fait du sens. Tu pourras l'intégrer si c'est la bonne façon de faire et que tu juges que ça pourrais bénéficier à d'autres personnes.
Merci pour ton temps!

**Comment by Tundra-bit** [comment]
Salut, 
Merci pour le travaille sur cette extension, très apprécié

J'ai toujours cette problematique:

Le vidéo démarre mais l'animation de progression de téléchargement (rond bleu sous le skin Estuary) reste affiché pendant la durée complète du vidéo

Merci

**Comment by anisite** [comment]
Bonsoir, 
je viens d'effectuer un correctif, je suis un peu à l'aveugle puisque le problème ne survient pas chez moi… vous pouvez forcer la MAJ, tenez moi au courant.

**Comment by anisite** [comment]
Aucune activité/réponse
