### ISSUE TITLE
Les steam ne fonctionne plus

### ISSUE THREAD

**Issue by mbelang** [anisite/plugin.infologique.tou.tv#18]
Depuis quelques jours les streams ne fonctionne plus. J'ai eu le même problème pour avec télé Québec, je ne sais pas si c'est relié.

https://github.com/dualB/plugin.video.telequebec/issues/14

**Comment by anisite** [comment]
Bonjour, est-ce possible d'avoir une description du problème? Rien ne se passe quand vous lancez une émission? Rien du tout? Je viens d'essayer ici et ça a pris beaucoup de temps mais j'ai eu un popup pour mettre à jour widevine. Et ensuite tout fonctionne, avez vous eu ce popup?

**Comment by mbelang** [comment]
La dernière fois que j'ai essayé rien ne se passait. Il y avait la loading wheel et elle disparaissait puis rien. Je suis habitué de voir le popup d'update de widevine mais je ne l'ai pas vu. Je peux réessayer.

**Comment by anisite** [comment]
Il me faudrait alors la version kodi, l'OS utilisé, si possible le log kodi pour voir l'erreur. Sinon c'est difficile à corriger...

**Comment by mbelang** [comment]
LibreELEC 9.2.5
Kodi 18.8

Je vais envoyer le log bientôt

**Comment by anisite** [comment]
Pas eu de suivi
