### ISSUE TITLE
Problème lors de la récupération de la liste d'épisodes

### ISSUE THREAD

**Issue by MartChic** [anisite/plugin.infologique.tou.tv#19]
Depuis quelques jours il y a régulièrement des erreurs quand j'essaie de récupérer la liste d'épisodes de District 31, entre autres. Voir le log à partir de la ligne : 

2020-11-30 19:51:56.208 T:1936990224 WARNING: Previous line repeats 12 times.

https://pastebin.com/aa8PJHM8

**Comment by anisite** [comment]
C'est intermittent?

**Comment by MartChic** [comment]
Ça semble intermittent, en effet. Je l'ai justement essayé hier et ça fonctionnait.

**Comment by MartChic** [comment]
Le problème est toujours présent.

Merci beaucoup pour le travail et bonne année !

**Comment by anisite** [comment]
<urlopen error timed out> il semble manquer de temps ... je ne sais pas pourquoi parce que le timeout par défaut est infiniment long... est-ce que tu attends longtemps avant que ça arrive ? (chargement de X temps ?)

**Comment by MartChic** [comment]
Quand je clique sur l'émission, le "sablier" apparaît et il disparaît tout seul après quelque chose comme 15 secondes. Il ne se passe rien ensuite.

**Comment by MartChic** [comment]
Quand ça fait ça, je réessaye et ça finit par marcher après quelques essais.
