### ISSUE TITLE
Lecture video

### ISSUE THREAD

**Issue by laboiteadroid** [anisite/plugin.infologique.tou.tv#20]
Salut, lorsque je choisi un contenu, il est lu par Kodi comme si c'était de la musique. J'ai le son, mais pas de vidéo. Comme si Kodi recevait un flux audio de musique.
Sur Android (Firestick), Kodi 18.9
Merci

**Comment by anisite** [comment]
Est-ce que ça a dejà fonctionné?

**Comment by laboiteadroid** [comment]
Salut, oui
J'ai trouvé justement hier, dans Kodi l'accélération hardware était
enlever, j'ai remis et ça fonctionne.
Merci d'avoir prise temps

Daniel
