### ISSUE TITLE
Lecture d'un film fail

### ISSUE THREAD

**Issue by Kirija** [anisite/plugin.infologique.tou.tv#21]
Salut,

(Je suis abonné à IciTouTV, mon profil est bien pris en compte)
Lorsque je lance un film (il apparait comme série donc il faut manipuler pas mal pour réussir à le lancer via "Lire") j'ai un message du serveur : "Claim's authorization reader value not equal to the initial one used for the get claims request." Je ne peux faire que OK, je le fais, spinning wheel forever, escape puis échec de lecture mais rien dans le journal.
KODI 18.7 git20200612
Raspi3B+ RaspiOS 5.4.79-v7+

**Comment by anisite** [comment]
Tou.tv ont peut-être reserrés leur sécurité je vais essayer de voir en fds... je travail pas mal ces temps-ci, je vais faire ce que je peux

**Comment by Kirija** [comment]
J'aurais bien enquêté par moi même mais je viens d'installer l'extension donc je ne connais pas le comportement "normal" : temps d'attente et présentation des affaires.
