### ISSUE TITLE
Kodi 19 support

### ISSUE THREAD

**Issue by Kameleau** [anisite/plugin.infologique.tou.tv#22]
Bonjour, j'aimerais bien passer à Kodi 19 (en particulier pour le support 4K/HDR), mais l'appli tou.tv que j'utilise régulièrement ne semble pas compatible à cause qu'elle est en Python 2.

Est-ce qu'une version compatible Kodi 19 en Python 3 sera disponible bientôt?

Merci

**Comment by anisite** [comment]
Avez vous des difficultés avec tou.tv sur Kodi 18 ? Pour le support de kodi 19 j'avais regardé mais ça semblait pas siii simple et quick... il va me falloir un break des enfants!

**Comment by Kameleau** [comment]
Non, je n'ai aucun problème avec tou.tv sur Kodi 18. Tel que mentionné, Kodi 19 supporte mieux le 4k en HDR, mais pour l'instant je reste sur Kodi 18 à cause de tou.tv car je l'utilise à chaque jour. De plus, Kodi 19 est maintenant en version Beta 2 donc la version finale s'en vient bientôt. En espérant que vous aurez le temps de rendre tou.tv compatible un moment donné, merci! :)

**Comment by anisite** [comment]
Je ne sais pas combien de Beta ils feront mais ensuite il y aura toutes les Releases Candidates, on en as au moins jusqu'à fin janvier si pas plus. Je vais regarder à nouveau dans le temps des fêtes mais ça semble assez complexe de gérer les 2 pythons en parallèle. à suivre.

**Comment by anisite** [comment]
Bonjour @Kameleau je viens de pousser une version 5.0.0 alpha qui supporte maintenant python 2 et 3 (la MàJ est disponible manuellement dans les informations de l'addon) si vous voulez faire un test avec Kodi 18 et ensuite avec Kodi 19 ce serait apprécié! merci!

**Comment by Kameleau** [comment]
Bonjour, j'ai commencer par mettre à jour l'addon dans Kodi 18 et tout semblais toujours bien marcher. Puis j'ai fait l'update à Kodi 19 (sans effacer mon userdata avant, pour tester) et tout semble toujours bien fonctionner. Mon compte est toujours actif pour les Extra, les favoris, lu/non-lus, reprendre une lecture fonctionne bien. Le démarrage d'une lecture semble plus rapide en bonus.

Je continue de l'utiliser comme d'habitude et je te revient si je trouve des bugs. Merci beaucoup!

**Comment by Kameleau** [comment]
Je voie que tu contribue aussi pour Noovo et TVA, si jamais tu as le temps.. :) 👍

**Comment by MartChic** [comment]
J'ai installé 5.0.0 avec Kodi 18 (Libreelec) et tout semble fonctionner normalement.

**Comment by anisite** [comment]
@MartChic  ça corrige ton bug de timeout? Pour Noovo c'est dans les plans. TVA je ne maintiens plus ça.

**Comment by MartChic** [comment]
> @MartChic ça corrige ton bug de timeout? Pour Noovo c'est dans les plans. TVA je ne maintiens plus ça.

Je n'ai pas eu de problème depuis que j'ai fait la mise à jour. Je te dirai si ça revient.

**Comment by MartChic** [comment]
> 
> 
> > @MartChic ça corrige ton bug de timeout? Pour Noovo c'est dans les plans. TVA je ne maintiens plus ça.
> 
> Je n'ai pas eu de problème depuis que j'ai fait la mise à jour. Je te dirai si ça revient.

Ce problème existe encore, ça m'est arrivé hier.
