### ISSUE TITLE
Possibilité de faire jouer le prochain épisode

### ISSUE THREAD

**Issue by esaudet** [anisite/plugin.infologique.tou.tv#24]
Je crois que par défaut dans kodi il y a la possibilité de faire jouer le prochain épisode lorsqu'on écoute une série. Par contre, cela ne semble pas disponible dans l'addon présentement. Est-ce beaucoup d'implication pour en ajouter le support?

Voici une capture d'écran de la barre d'action de l'addon :

![Capture d’écran de 2021-05-30 23-54-07](https://user-images.githubusercontent.com/32800206/120137765-05702e00-c1a3-11eb-863c-424b02ed54a5.png)

Et un exemple de barre d'action de l'addon netflix : https://github.com/CastagnaIT/plugin.video.netflix

![Capture d’écran de 2021-05-30 23-54-58](https://user-images.githubusercontent.com/32800206/120137803-1caf1b80-c1a3-11eb-8929-b958e4cdcb7e.png)

Merci!

**Comment by anisite** [comment]
C'est probablement faisable mais honnêtement je ne crois pas que j'y mettrait le temps, je m'en tiens au minimum de dev parce que les addons peuvent cassés du jour au lendemain quand le site est mis à jour.
