### ISSUE TITLE
Vidéo Tou.tv ne fonctionne pas

### ISSUE THREAD

**Issue by maxdarude** [anisite/plugin.infologique.tou.tv#25]
Depuis 5 jours environ, les vidéos se lancent (icône des chargement apparaît, disparaît et revient ) mais les vidéos ne jouent pas, et revient à l’écran de sélection. 
kodi 18.9
Tou.tv 5.0

**Comment by anisite** [comment]
bonjour normalement les addons ne sont plus supportés, mais je vais p-e pouvoir regarder cette semaine rapidement au cas ou ce serait simple a corriger.

**Comment by anisite** [comment]
Avez-vous un exemple d'émission et êtes-vous connecté ou non dans l'addon?

**Comment by Carle1961** [comment]
Même problème ici (kodi 18.2).  Ca semble est du au DRM qui nécessite la dernière version de Widevine mais cette version de Widevine ne semble pas compatible avec Kodi 18.

**Comment by maxdarude** [comment]
> Avez-vous un exemple d'émission et êtes-vous connecté ou non dans l'addon?

La galère (saison 3 ep 1)
Le pharmacien (saison 3 ep4)
L’épicerie 
Je suis connecté avec un compte extra

**Comment by anisite** [comment]
Linux, Android tv, Windows?

**Comment by Carle1961** [comment]
Raspbian 9 and 10

**Comment by Carle1961** [comment]
Pas certain de comprendre ce que j'ai fait mais tout fonctionne maintenant.
J'ai installé manuellement InputStream Helper v0.4.7 (https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/tag/v0.4.7). Ensuite j'ai fait la mise à jour de l'addon InputStream Helper à 0.5.8 à partir de Kodi (je n'étais pas capable de faire la mise à jour à partir de Kodi avant, toujours l'erreur de Python 3.0.0). Puis j'ai fait la mise à jour de l'addon tout.tv 5.0.

Plusieurs mise à jour me donnait l'erreur: The dependency on xbmc.python version 3.0.0 could not be satisfied. Tout semble avoir été réglé depuis.

**Comment by anisite** [comment]
Ça risque de vous arriver de plus en plus ce genre d'erreurs, Kodi 19 est disponible depuis deja 9 mois, il faudrait songer à mettre à jour....

**Comment by maxdarude** [comment]
Il semble que la mise à jour automatique de Kodi par OSMC échouait à chaque essaie. J'ai du me connecter en SSH au raspberry PI pour accepter le changement de nom des dépots de OSMC et j'ai pu upgrader à Kodi 19.
maintenant Tou.tv fonctionne. (d'autres add-on plus maintenant). 
Comme j'ai mis à jour mon système. le problème est résolu.
Kodi 19 = OK
kodi 18 = aucune résolution.
Merci :)
