### ISSUE TITLE
AUTHENTIFICATION auprès de ici.tou.tv ne fonctionne plus.

### ISSUE THREAD

**Issue by abracadabrapare** [anisite/plugin.infologique.tou.tv#26]
Si on enlève l'identifiant et le mot de passe associé, l'addon fonctionne sans le contenu EXTRA.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                Error Type: <class 'urllib.error.HTTPError'>
                                                Error Contents: HTTP Error 500: Internal Server Error
                                                Traceback (most recent call last):
                                                    File "/storage/.kodi/addons/plugin.infologique.tou.tv/default.py", line 1, in <module>
                                                    from resources.lib.toutv import Main
                                                    File "/storage/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 53, in <module>
                                                    LOGIN             = scraper.CheckLogged()
                                                    File "/storage/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 187, in CheckLogged
                                                    TEST()
                                                    File "/storage/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 303, in TEST
                                                    content = CALL_HTML_AUTH('https://services.radio-canada.ca/toutv/profiling/accounts/login?device=web&version=4',"POST", json.dumps(POST), "client-key " + clientKey)
                                                    File "/storage/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 248, in CALL_HTML_AUTH
                                                    response = opener.open(request)
                                                    File "/usr/lib/python3.8/urllib/request.py", line 531, in open
                                                    File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
                                                    File "/usr/lib/python3.8/urllib/request.py", line 569, in error
                                                    File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
                                                    File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
                                                urllib.error.HTTPError: HTTP Error 500: Internal Server Error
                                                -->End of Python script error report<--

**Comment by SilverCloak** [comment]
J’ai le même problème depuis deux jours sur la version 18 et 19…. Étrange…

**Comment by anisite** [comment]
bonsoir, c'est très normal la SRC a changé sa méthode de login, c'est rendu un AD dans azure... va falloir que je change le login, aucune idée quand je vais avoir le temps. si qqun veut proposer un pull request je suis open!

**Comment by anisite** [comment]
J'ai débuté le code, c'est pas encore fonctionnel, à suivre

**Comment by anisite** [comment]
Je viens de livrer la version 5.1.0 avec le nouveau login, ça fonctionne sur Kodi 19 pas eu le temps de tester 18 encore ! Dites-moi si ça marche.

**Comment by erikatremblay** [comment]
Non fonctionnel sur kodi 18.9 avec un compte tou.tv

**Comment by anisite** [comment]
@erikatremblay très possible, c'est à cause du très vieux python 2.0 assez limité... il faut tout coder en double pratiquement. quand ça marche pour un l'autre ne fonctionne plus.. c'est très tannant, je compte supporter kodi 18.x jusqu'à la fin de l'année, ensuite je ne m'en préoccuperait plus, kodi 19 aura 1 an, c'est amplement de temps pour faire les mises à jour. par contre c'est deja plus dans mes priorités. merci du signalement! je tente de faire qqchose dès que possible.

**Comment by abracadabrapare** [comment]
@anisite

KODI 19.1.0
LIBREELEC 10.0.0
RPi4.ARM

Incroyable! Tout a fonctionné du premier coup. Qu'est-ce qu'on serait, nous, les utilisateurs de KODI, sans vous, Anisite?
Vous venez de faire plein d'heureux dans mon entourage, qui regardent tou.tv. Mille mercis pour votre réponse si rapide, bénévole de surcroît.

**Comment by erikatremblay** [comment]
@anisite merci beaucoup, super apprécié! Je comprends que cela doit être désagréable, et je vous remercie de bien vouloir continuer votre bon travail jusqu’à la fin de l’année.

kodi 19 n’est pas encore super au point selon moi car beaucoup d’addons ne fonctionnent pas avec kodi 19 😔 Je vais tout de même commencer à faire un build avec kodi 19, mais beaucoup de choses ne sont pas supporter encore.

**Comment by anisite** [comment]
@erikatremblay c'est dommage mais si ce n'est pas encore supporté ça ne le sera probablement jamais. les addons sont peut être simplement abandonnés par leur concepteur (devant la montagne de code à migrer) je propose de faire pression sur les concepteurs de ces addons la pour qu'ils fasse le pas...

**Comment by erikatremblay** [comment]
@anisite vous êtes certain que c’est la seule raison, car j’utilise des addons pas mal mis a jour tous le temps pourtant 🤔

moi je me suis fait dire que les concepteurs de kodi ne voulaient plus de streaming illégal donc les addons qui utilisent des liens gratuits ne feront pas le pas vers kodi 19 🤔 a moins que la personne a qui j’ai parler c’est tromper 🤷‍♀️ Je vais voir si mes addons sont supporter et vous reviens 😉

**Comment by anisite** [comment]
@erikatremblay https://kodi.tv/article/kodi-broke-my-addons/

**Comment by erikatremblay** [comment]
Bon, j’ai plusieurs addons non compatible encore malheureusement avec kodi 19 dont L’addon tele-quebec du dépôt quebec qui n’est même pas dans la liste avec kodi 19. 😔

**Comment by anisite** [comment]
@erikatremblay Bonne nouvelle. La version 5.1.1 est en cours de déploiement, elle devrait corriger le problème de python 2.

**Comment by erikatremblay** [comment]
@anisite ohhh merci beaucoup 🤩

**Comment by erikatremblay** [comment]
@anisite merci sa fonctionne a merveille 🙊☺️
