### ISSUE TITLE
tou.tv kodi 19.2 - bitrate in content["bitrates"]:  ERROR: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by motosba** [anisite/plugin.infologique.tou.tv#28]
Impossible de jouer un épisode :

WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
ERROR <general>: Traceback (most recent call last):
                                                   
ERROR <general>: 
ERROR <general>:   File "/home/user/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 223, in __init__
                                                       try: player.playVideoExtra( self.args.PIDEXTRA, self.args.KEY, startoffset=self.args.starttime )
                                                   
ERROR <general>: 
ERROR <general>:   File "/home/user/.kodi/addons/plugin.infologique.tou.tv/resources/lib/TouTvPlayer.py", line 85, in playVideoExtra
                                                       data = getVideoExtra( PID )
                                                   
ERROR <general>: 
ERROR <general>:   File "/home/user/.kodi/addons/plugin.infologique.tou.tv/resources/lib/scraper.py", line 108, in getVideoExtra
                                                       for bitrate in content["bitrates"]:
                                                   
ERROR <general>: 
ERROR: 'NoneType' object is not iterable
                                                   
ERROR <general>: 
INFO <general>: CPythonInvoker(14, /home/user/.kodi/addons/plugin.infologique.tou.tv/default.py): script successfully run
INFO <general>: initializing python engine.
WARNING <general>: CPythonInvoker(14, /home/user/.kodi/addons/plugin.infologique.tou.tv/default.py): the python script "/home/user/.kodi/addons/plugin.infologique.tou.tv/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
INFO <general>: Python interpreter stopped
WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
ERROR <general>: NEWADDON Invalid Date Format "2021-10-17 04:00:00"
ERROR <general>: NEWADDON Invalid Date Format "2021-10-10 04:00:00"
ERROR <general>: NEWADDON Invalid Date Format "2021-10-03 04:00:00"
ERROR <general>: NEWADDON Invalid Date Format "2021-09-26 04:00:00"
ERROR <general>: NEWADDON Invalid Date Format "2021-05-30 04:00:00"
ERROR <general>: NEWADDON Invalid Date Format "2021-05-23 04:00:00"
ERROR <general>: NEWADDON Invalid Date Format "2021-05-16 04:00:00"
ERROR <general>: NEWADDON Invalid Date Format "2021-05-09 04:00:00"
ERROR <general>: NEWADDON Invalid Date Format "2021-05-02 04:00:00"
ERROR <general>: NEWADDON Invalid Date Format "2021-04-25 04:00:00"
ERROR <general>: NEWADDON Invalid Date Format "2021-04-18 04:00:00"
INFO <general>: CPythonInvoker(15, /home/user/.kodi/addons/plugin.infologique.tou.tv/default.py): script successfully run
WARNING <general>: CPythonInvoker(15, /home/user/.kodi/addons/plugin.infologique.tou.tv/default.py): the python script "/home/user/.kodi/addons/plugin.infologique.tou.tv/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
INFO <general>: Python interpreter stopped

**Comment by anisite** [comment]
L'erreur semble plutôt la liste des bitrates qui est vide. Quel émission fait ce problème?

**Comment by motosba** [comment]
Il s'agit de Tout le monde en parle.

Merci

**Comment by anisite** [comment]
Idem https://github.com/anisite/plugin.infologique.tou.tv/issues/29

**Comment by anisite** [comment]
@motosba j'ai publié la version 5.1.2 pouvez vous me dire la version de l'addon que vous avez? Et si c'est avec un compte, sans compte avec EXTRA ou non, merci

**Comment by motosba** [comment]
@anisite j'ai refait un essaie avec un autre VPN basé à Toronto et ça fonctionne. Ça me parait géo-bloqué avec certains fournisseurs VPN et l'erreur est toujours la même "'NoneType' object is not iterable". Ça fonctionne partout sinon à MTL où j'ai testé. Sans compte extra. Version 5.1.2 maintenant, j'utilisais la précédente auparavant.
Merci :)!

**Comment by anisite** [comment]
Si c'est en raison de la position géographique, je ne crois pas que je puisse faire quoi que ce soit...
