### ISSUE TITLE
tou.tv kodi 19.3 android tv (v11) et android v12

### ISSUE THREAD

**Issue by motosba** [anisite/plugin.infologique.tou.tv#29]
Impossible de jouer les épisodes d'infoman ou tout le monde en parle. Fonctionne bien sur Linux autrement.
    
ERROR <general>: Control 500 in window 10025 has been asked to focus, but it can't
     INFO <general>: initializing python engine.
  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
    ERROR <general>: NEWADDON Unknown Video Info Key "label"
     INFO <general>: Skipped 165 duplicate messages..
     INFO <general>: CPythonInvoker(11, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py): script successfully run
  WARNING <general>: CPythonInvoker(11, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
     INFO <general>: Python interpreter stopped
     INFO <general>: initializing python engine.
  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
    ERROR <general>: NEWADDON Invalid Date Format "2021-12-09 05:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-12-02 05:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-11-25 05:00:00"
   ERROR <general>: NEWADDON Invalid Date Format "2021-11-18 05:00:00"
   ERROR <general>: NEWADDON Invalid Date Format "2021-11-11 05:00:00"
   ERROR <general>: NEWADDON Invalid Date Format "2021-11-04 04:00:00"
   ERROR <general>: NEWADDON Invalid Date Format "2021-10-28 04:00:00"
   ERROR <general>: NEWADDON Invalid Date Format "2021-10-21 04:00:00"
   ERROR <general>: NEWADDON Invalid Date Format "2021-10-14 04:00:00"
   ERROR <general>: NEWADDON Invalid Date Format "2021-10-07 04:00:00"
   ERROR <general>: NEWADDON Invalid Date Format "2021-09-30 04:00:00"
   ERROR <general>: NEWADDON Invalid Date Format "2021-09-23 04:00:00"
   ERROR <general>: NEWADDON Invalid Date Format "2021-09-16 04:00:00"
    INFO <general>: CPythonInvoker(12, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py): script successfully run
 WARNING <general>: CPythonInvoker(12, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
    INFO <general>: Python interpreter stopped
    INFO <general>: initializing python engine.
 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
   ERROR <general>: Traceback (most recent call last):

   ERROR <general>: 
   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 223, in __init__
  try: player.playVideoExtra( self.args.PIDEXTRA, self.args.KEY, startoffset=self.args.starttime )

   ERROR <general>: 
   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/resources/lib/TouTvPlayer.py", line 85, in playVideoExtra
  data = getVideoExtra( PID )

   ERROR <general>: 
   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/resources/lib/scraper.py", line 108, in getVideoExtra
  for bitrate in content["bitrates"]:

   ERROR <general>: 
   ERROR <general>: TypeError: 'NoneType' object is not iterable

   ERROR <general>: 
    INFO <general>: CPythonInvoker(13, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py): script successfully run
    INFO <general>: initializing python engine.
 WARNING <general>: CPythonInvoker(13, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
     INFO <general>: Python interpreter stopped
  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
    ERROR <general>: NEWADDON Invalid Date Format "2021-12-09 05:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-12-02 05:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-11-25 05:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-11-18 05:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-11-11 05:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-11-04 04:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-10-28 04:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-10-21 04:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-10-14 04:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-10-07 04:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-09-30 04:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-09-23 04:00:00"
    ERROR <general>: NEWADDON Invalid Date Format "2021-09-16 04:00:00"
     INFO <general>: CPythonInvoker(14, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py): script successfully run
  WARNING <general>: CPythonInvoker(14, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.infologique.tou.tv/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
     INFO <general>: Python interpreter stopped

**Comment by anisite** [comment]
doublon

**Comment by anisite** [comment]
@motosba quelle version de l'addon Tou.tv avez vous ?
