### ISSUE TITLE
Les échangistes

### ISSUE THREAD

**Issue by theminibergy** [anisite/plugin.infologique.tou.tv#3]
Bonjour,

je suis incapable d'écouter les échangistes.
je suis à version 3.0.1 sur kodi 17
aucun vidéo ne semble fonctionner.

merci

**Comment by toto9888** [comment]
Bonjour, 

Même chose pour moi, Kodi 17 avec la version 3.0.1 
Les émissions de Radio-Canada ne fonctionne plus.

**Comment by anisite** [comment]
Il est possible de retourner en arrière a partir du dépôt pour prendre la dernière bonne version pour vous. Mais c'est certain que la nouvelle version a été faite pour le contenu crypté et il faut théoriquement Kodi 18. Si vous êtes prêts pour essayer la nouvelle version en beta allez y sinon il faudrait qu'un de vous au moins me fournisse le log après avoir reproduit le bug.

**Comment by toto9888** [comment]
voici le kodi.log juste après avoir reproduis l'erreur

https://pastebin.com/jR605HVy

**Comment by toto9888** [comment]
J'ai mis à jour à Kodi 18 et j'ai le même problème

**Comment by anisite** [comment]
dans ton log: Error getting /usr/lib/kodi/addons/inputstream.adaptive/
est-ce possible d'essayer de l'Activer manuellement comme ceci : http://www.best-kodi-guides.eu/kodi-add-on-reviews/enable-inputstream-adaptive-kodi-krypton/  merci!

**Comment by toto9888** [comment]
il est déjà activé bien activé.

**Comment by anisite** [comment]
@toto9888 êtes-vous abonné Extra et utilisez-vous l'addon en "invité" ou avec un compte ?

**Comment by toto9888** [comment]
J'ai un compte extra. Mais j'ai aussi essayer en mode normal.

**Comment by anisite** [comment]
Bonsoir, j'ai déployé une nouvelle version ce PM avec une meilleure gestion des comptes gratuit (invités) et une nouvelle option dans les paramètres pour désactiver les flux protégés (utiliser des versions non chiffrés des émissions) cette option fonctionne pour tout ce qui n'est pas "films" et autres trucs plus protégés, pour le moment uniquement, parce que je sens que radio-canada améliore tranquillement ses protections.

Donc, pour ceux que le vidéos sont noirs ou s'ils ne démarrent pas, passez à Kodi 18 et/ou désactivez les DRM dans les options de l'addon. (il arrive que sur certaines plate-forme comme raspberry pi il n'y a pas de widevine v1 ni v2 donc le décodage ne fonctionne pas et pour le moment il faudra désactiver les DRM...)

Merci de me tenir au courant de vos essais !

**Comment by thibaulf** [comment]
Il semble que le plugin est instable de mon côté: le menu d’accueil ne s’affiche pas du tout. Je ressort de l’application et ça se met à marcher. Un peu intermittent comme problème
