### ISSUE TITLE
Impossible de lire des vidéos

### ISSUE THREAD

**Issue by franckgaga** [anisite/plugin.infologique.tou.tv#33]
Bonjour,

Depuis environ 2 semaines il est impossible de lire des vidéos dans le plugin tou.tv.

J'utilise LibreELEC v12.0.0  (Kodi 21) sur un RPi 4

Voici un log de mon système (j'ai tenté de lire 1 émission dans celui-ci):

https://paste.libreelec.tv/coherent-owl.log

Merci!

**Comment by anisite** [comment]
Bonjour est-ce que ça pourrait avoir un lien?

https://github.com/anisite/DepotQuebec/issues/97

**Comment by franckgaga** [comment]
Non, j'ai bel et bien la dernière version de InputStream Adaptative. 

J'ai cenpendant ré-installé la dernière version de Widevine avec le InputSteam Helper et le problème semble reglé!

Encore merci et sorry for the noise!
