### ISSUE TITLE
Plugin Brisé

### ISSUE THREAD

**Issue by gabtremblay** [anisite/plugin.infologique.tou.tv#7]
Semblerait qu'il y ait eu une mise a jour de tou.tv dans la nuit du 6 au 7 juin. 

Aurais-tu un petit guide "point-form" de 5-10 lignes qui explique ton processus quand tu debug l'app ex:
1- Burp proxy / in-browser debug pour valider les nouveaux paths
2- Utiliser une instance windows/mac de kodi pour debug
3- Modifier habituellement fichier x,y,z

C'est un peu paresseux de ma part de demander ça, mais ça me ferait plaisir de te pousser des pull requests quand des changements mineurs comme ça surviennent.

**Comment by maxmasou** [comment]
Même netflix ne change pas leur code aussi souvent. Il y a vraiment du monde payé a rien faire chez radio-canada! Gang de cabochon...

**Comment by maxmasou** [comment]
Finalement c'est simplement un petit problème mineur. Il suffit de remplacer "client-key 4dd36440-09d5-4468-8923-b6d91174ad36" par "client-key 90505c8d-9c34-4f34-8da1-3a85bdc6d4f4" dans tous les fichiers. Je vais proposer une modification temporaire d'ici demain matin. Mais il serait préférable d'obtenir la valeur à chaque démarrage de l'addon dans le futur. Par contre @anisite est probablement plus qualifié que moi pour proposer la modification finale!

**Comment by gabtremblay** [comment]
Je confirme le commentaire de @maxmasou 

J'ai passé un petit 30 minutes à tenter de déterminer si cette clef était "par utilisateur" ou simplement en place pour authentifier la version de leur client. Il semble que cette clef soit la même pour tout les utilisateurs, donc il est fiable de se dire que la clef précédente n'a pas été "bannie" et qu'il n'y a aucun risque pour un compte précis d'utiliser cette valeur à tout les endroits. Elle est bel et bien en place pour authentifier la version du client.

D'ailleurs, cette clef peut être retrouvée dans le fichier suivant:

https://ici.tou.tv/app.js

En recherchant la chaîne
"client-key"

On tombe sur:
{Authorization:"client-key ".concat("90505c8d-9c34-4f34-8da1-3a85bdc6d4f4")})}

Aucun besoin de suivre le lien "versionné" que l'on trouve au bas du fichier html de la page principale.

Si personne ne le fait j'ajouterai un peu de "scraping code" pour automatiser le tout ce weekend.

**Comment by maxmasou** [comment]
Je viens de proposer le commit qui règle le problème temporairement. Pour ceux qui ne peuvent pas attendre, télécharger la modification sur https://github.com/maxmasou/plugin.infologique.tou.tv/

**Comment by anisite** [comment]
Pas de chance, j'ai fais le même changement! La clé peut être retrouvée ailleurs aussi. dans le fichier de settings de l'application. je vais ajouter un fetch du fichier afin d'obtenir la clée a jour, si jamais ils la rechange, mais ça c'est pas ce soir.

**Comment by anisite** [comment]
@gabtremblay Bonne question, pour tou.tv, j'ai pris fiddler, j'ai aussi décompilé l'apk android pour avoir l'adresse des API et connaître les clés pour décoder les flux video plus "simples" que la version "client web" sinon c'est juste des tests avec les appels http... c'est pas mal ça

**Comment by maxmasou** [comment]
Pas de trouble. Continue ton beau travail. J'ai toujours un mal de tête qui me pogne quand je me met a étudier le code. C'est beaucoup plus ton domaine que le mien! loll :)

**Comment by gabtremblay** [comment]
Effectivement, merci encore pour le travail.

**Comment by anisite** [comment]
@maxmasou le code est tout croche... Le plugin est rendu à sa 6 ième refonte d'Api... Il faudrait faire du ménage mais j'ai pas l'énergie avec mes deux jeunes garçons...

**Comment by maxmasou** [comment]
@anisite 
Pas de trouble! Sans rien promettre, je vais regarder ce que je peux faire...

**Comment by thibaulf** [comment]
J'ai écrit un peu de code pour aller chercher automatiquement le client-ID sur le site de tou.tv 
https://github.com/thibaulf/plugin.infologique.tou.tv

**Comment by maxmasou** [comment]
@thibaulf 
Beau travail!

**Comment by anisite** [comment]
Tel que spécifié plus haut la clé est dans la config de l'application, j'avais mis l'adresse partielle dans le changelog https://services.radio-canada.ca/toutv/presentation/settings?device=web&version=4 le fichier est en JSON donc pas de fling flang pour rechercher

**Comment by thibaulf** [comment]
Effectivement, beaucoup plus simple ! j'adore pas particulièrement les expressions régulières !

**Comment by thibaulf** [comment]
> Tel que spécifié plus haut la clé est dans la config de l'application, j'avais mis l'adresse partielle dans le changelog https://services.radio-canada.ca/toutv/presentation/settings?device=web&version=4 le fichier est en JSON donc pas de fling flang pour rechercher

Effectivement, beaucoup plus simple ! j'adore pas particulièrement les expressions régulières !

**Comment by anisite** [comment]
Je vais faire un merge de tout ça demain merci!

**Comment by thibaulf** [comment]
Cool, merci
